#!/bin/bash  
set -euo pipefail  
  
# Migration script generated by emt-migrate  
# Source: emt-edge-node-01  
# Target distro: suse  
# Generated: 2025-03-15 10:00:00  
# Packages: 8  
  
CHECKPOINT_DIR="/var/lib/emt-migrate"  
mkdir -p "$CHECKPOINT_DIR"  
  
checkpoint_done() {  
    [ -f "$CHECKPOINT_DIR/$1.done" ]  
}  
  
mark_done() {  
    touch "$CHECKPOINT_DIR/$1.done"  
}  
  
echo "=== EMT Migration Script ==="  
echo "Target: suse"  
  
# --- Phase 1: Install RPM packages ---  
if ! checkpoint_done "packages"; then  
    echo "Installing packages..."  
    zypper install -y \  
        kernel \
        tdnf \
        docker-engine \
        openvino-runtime \
        systemd \
        openssl \
        curl \
        python3  
    mark_done "packages"  
else  
    echo "Packages already installed, skipping..."  
fi  
  
# --- Phase 2: Load Docker images ---  
  
if ! checkpoint_done "docker_openvino_model_server"; then  
    echo "Loading Docker image: openvino/model_server:latest"  
    docker pull "openvino/model_server:latest" || echo "Warning: Failed to pull openvino/model_server:latest"  
    mark_done "docker_openvino_model_server"  
fi  
  
if ! checkpoint_done "docker_edge-ai-suite_pipeline"; then  
    echo "Loading Docker image: edge-ai-suite/pipeline:v2.1"  
    docker pull "edge-ai-suite/pipeline:v2.1" || echo "Warning: Failed to pull edge-ai-suite/pipeline:v2.1"  
    mark_done "docker_edge-ai-suite_pipeline"  
fi  
  
  
echo "=== Migration complete ==="  
