// cmd/generate.go
package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/Maya-Mohamed/emt-migrate/pkg/snapshot"
	"github.com/spf13/cobra"
)

var (
	snapshotFile string
	targetDistro string
	scriptOutput string
)

const migrationScriptTemplate = `#!/bin/bash  
set -euo pipefail  
  
# Migration script generated by emt-migrate  
# Source: {{.Hostname}}  
# Target distro: {{.Target}}  
# Generated: {{.Timestamp}}  
# Packages: {{.PackageCount}}  
  
CHECKPOINT_DIR="/var/lib/emt-migrate"  
mkdir -p "$CHECKPOINT_DIR"  
  
checkpoint_done() {  
    [ -f "$CHECKPOINT_DIR/$1.done" ]  
}  
  
mark_done() {  
    touch "$CHECKPOINT_DIR/$1.done"  
}  
  
echo "=== EMT Migration Script ==="  
echo "Target: {{.Target}}"  
  
# --- Phase 1: Install RPM packages ---  
if ! checkpoint_done "packages"; then  
    echo "Installing packages..."  
    {{.PackageManager}} install -y \  
{{.PackageList}}  
    mark_done "packages"  
else  
    echo "Packages already installed, skipping..."  
fi  
  
# --- Phase 2: Load Docker images ---  
{{range .DockerImages}}  
if ! checkpoint_done "docker_{{.SafeName}}"; then  
    echo "Loading Docker image: {{.Repository}}:{{.Tag}}"  
    docker pull "{{.Repository}}:{{.Tag}}" || echo "Warning: Failed to pull {{.Repository}}:{{.Tag}}"  
    mark_done "docker_{{.SafeName}}"  
fi  
{{end}}  
  
echo "=== Migration complete ==="  
`

type scriptData struct {
	Hostname       string
	Target         string
	Timestamp      string
	PackageCount   int
	PackageManager string
	PackageList    string
	DockerImages   []dockerImageData
}

type dockerImageData struct {
	Repository string
	Tag        string
	SafeName   string
}

var generateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate migration script from a snapshot",
	RunE: func(cmd *cobra.Command, args []string) error {
		data, err := os.ReadFile(snapshotFile)
		if err != nil {
			return fmt.Errorf("failed to read snapshot: %w", err)
		}

		var snap snapshot.Snapshot
		if err := json.Unmarshal(data, &snap); err != nil {
			return fmt.Errorf("failed to parse snapshot: %w", err)
		}

		pkgManager := "dnf"
		if targetDistro == "suse" {
			pkgManager = "zypper"
		}

		var pkgLines []string
		for _, pkg := range snap.Packages {
			pkgLines = append(pkgLines, fmt.Sprintf("        %s", pkg.Name))
		}

		var dockerImgs []dockerImageData
		for _, img := range snap.DockerImages {
			safe := strings.ReplaceAll(img.Repository, "/", "_")
			safe = strings.ReplaceAll(safe, ":", "_")
			dockerImgs = append(dockerImgs, dockerImageData{
				Repository: img.Repository,
				Tag:        img.Tag,
				SafeName:   safe,
			})
		}

		tmplData := scriptData{
			Hostname:       snap.Hostname,
			Target:         targetDistro,
			Timestamp:      snap.Timestamp.Format("2006-01-02 15:04:05"),
			PackageCount:   len(snap.Packages),
			PackageManager: pkgManager,
			PackageList:    strings.Join(pkgLines, " \\\n"),
			DockerImages:   dockerImgs,
		}

		tmpl, err := template.New("migration").Parse(migrationScriptTemplate)
		if err != nil {
			return fmt.Errorf("template error: %w", err)
		}

		f, err := os.Create(scriptOutput)
		if err != nil {
			return fmt.Errorf("failed to create output: %w", err)
		}
		defer f.Close()

		if err := tmpl.Execute(f, tmplData); err != nil {
			return fmt.Errorf("template execution error: %w", err)
		}

		os.Chmod(scriptOutput, 0755)
		fmt.Printf("Migration script written to %s\n", scriptOutput)
		return nil
	},
}

func init() {
	generateCmd.Flags().StringVarP(&snapshotFile, "snapshot", "s", "snapshot.json", "Input snapshot file")
	generateCmd.Flags().StringVarP(&targetDistro, "target", "t", "rhel", "Target distro (rhel, fedora, centos, suse)")
	generateCmd.Flags().StringVarP(&scriptOutput, "output", "o", "migrate.sh", "Output script path")
	rootCmd.AddCommand(generateCmd)
}
