// cmd/generate.go
package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/Maya-Mohamed/emt-migrate/pkg/mapping"
	"github.com/Maya-Mohamed/emt-migrate/pkg/snapshot"
	"github.com/spf13/cobra"
)

var genSnapshot string
var genTarget string
var genOutput string

var scriptTemplate = `#!/bin/bash
set -euo pipefail

# Migration script generated by emt-migrate
# Source: {{ .Hostname }}
# Target distro: {{ .Target }}
# Packages: {{ .PackageCount }} ({{ .SkippedCount }} skipped, {{ .MappedCount }} mapped)

CHECKPOINT_DIR="/var/lib/emt-migrate"
mkdir -p "$CHECKPOINT_DIR"

checkpoint_done() {
    [ -f "$CHECKPOINT_DIR/$1.done" ]
}

mark_done() {
    touch "$CHECKPOINT_DIR/$1.done"
}

echo "=== EMT Migration Script ==="
echo "Target: {{ .Target }}"

{{ if .HasPackages }}
# --- Phase 1: Install RPM packages ---
if ! checkpoint_done "packages"; then
    echo "Installing {{ .PackageCount }} packages ({{ .SkippedCount }} EMT-only skipped)..."
    {{ .PkgManager }} install -y \
{{ .PackageList }}
    mark_done "packages"
else
    echo "Packages already installed, skipping..."
fi
{{ else }}
# --- Phase 1: No packages to install (all were EMT-only) ---
echo "No RPM packages to install (all packages were EMT-specific)."
{{ end }}
{{ range .DockerImages }}
# --- Docker: {{ .Repository }}:{{ .Tag }} ---
if ! checkpoint_done "docker_{{ .Repository | sanitize }}"; then
    echo "Loading Docker image: {{ .Repository }}:{{ .Tag }}"
    if [ -f "{{ .Repository | sanitize }}_{{ .Tag }}.tar" ]; then
        docker load -i "{{ .Repository | sanitize }}_{{ .Tag }}.tar"
    else
        docker pull "{{ .Repository }}:{{ .Tag }}" || echo "Warning: Failed to pull {{ .Repository }}:{{ .Tag }}"
    fi
    mark_done "docker_{{ .Repository | sanitize }}"
fi
{{ end }}
# --- Phase 3: Enable systemd services ---
{{ range .Services }}
if ! checkpoint_done "svc_{{ .Name | sanitize }}"; then
    echo "Enabling service: {{ .Name }}"
    systemctl enable {{ .Name }} || echo "Warning: Failed to enable {{ .Name }}"
    mark_done "svc_{{ .Name | sanitize }}"
fi
{{ end }}
echo "=== Migration complete ==="
`

type templateData struct {
	Hostname     string
	Target       string
	PkgManager   string
	PackageList  string
	PackageCount int
	SkippedCount int
	MappedCount  int
	HasPackages  bool
	DockerImages []snapshot.DockerImage
	Services     []snapshot.SystemdService
}

func sanitize(s string) string {
	r := strings.NewReplacer("/", "_", ":", "_", ".", "_", "-", "_")
	return r.Replace(s)
}

var generateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate a migration script for a target distribution",
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := mapping.ValidateTarget(genTarget); err != nil {
			return err
		}
		data, err := os.ReadFile(genSnapshot)
		if err != nil {
			return fmt.Errorf("failed to read snapshot: %w", err)
		}

		var snap snapshot.Snapshot
		if err := json.Unmarshal(data, &snap); err != nil {
			return fmt.Errorf("failed to parse snapshot: %w", err)
		}

		pkgManager := "dnf"
		if genTarget == "suse" {
			pkgManager = "zypper"
		}

		// Apply package mapping
		seen := make(map[string]bool)
		var pkgLines []string
		skipped := 0
		mappedCount := 0
		for _, pkg := range snap.Packages {
			targetName, skip, _ := mapping.MapPackage(pkg.Name, genTarget)
			if skip {
				skipped++
				continue
			}
			if seen[targetName] {
				continue // deduplicate
			}
			seen[targetName] = true
			if targetName != pkg.Name {
				mappedCount++
			}
			pkgLines = append(pkgLines, "        "+targetName+" \\")
		}

		pkgList := ""
		if len(pkgLines) > 0 {
			// Remove trailing backslash from last line
			pkgLines[len(pkgLines)-1] = strings.TrimSuffix(pkgLines[len(pkgLines)-1], " \\")
			pkgList = strings.Join(pkgLines, "\n")
		}

		funcMap := template.FuncMap{
			"sanitize": sanitize,
		}

		tmpl, err := template.New("script").Funcs(funcMap).Parse(scriptTemplate)
		if err != nil {
			return fmt.Errorf("failed to parse template: %w", err)
		}

		td := templateData{
			Hostname:     snap.Hostname,
			Target:       genTarget,
			PkgManager:   pkgManager,
			PackageList:  pkgList,
			PackageCount: len(pkgLines),
			SkippedCount: skipped,
			MappedCount:  mappedCount,
			HasPackages:  len(pkgLines) > 0,
			DockerImages: snap.DockerImages,
			Services:     snap.Services,
		}

		f, err := os.OpenFile(genOutput, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
		if err != nil {
			return fmt.Errorf("failed to create output file: %w", err)
		}
		defer f.Close()

		if err := tmpl.Execute(f, td); err != nil {
			return fmt.Errorf("failed to execute template: %w", err)
		}

		fmt.Printf("Migration script written to %s\n", genOutput)
		return nil
	},
}

func init() {
	generateCmd.Flags().StringVarP(&genSnapshot, "snapshot", "s", "snapshot.json", "Input snapshot file")
	generateCmd.Flags().StringVarP(&genTarget, "target", "t", "rhel", "Target distro (rhel, fedora, centos, suse)")
	generateCmd.Flags().StringVarP(&genOutput, "output", "o", "migrate.sh", "Output script path")
	rootCmd.AddCommand(generateCmd)
}
